import os
import sys

def bake_shaders(input_dir, output_file):
    # Ensure directory exists
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    
    if not os.path.exists(input_dir):
        print(f"Error: Shader directory not found at {input_dir}")
        return

    shader_files = [f for f in os.listdir(input_dir) if f.endswith(('.glsl', '.comp', '.vert', '.frag'))]
    
    with open(output_file, "w") as f:
        f.write("#pragma once\n\n")
        f.write("// This file is automatically generated. Do not edit manually.\n")
        f.write("#include <string>\n")
        f.write("#include <unordered_map>\n\n")
        f.write("namespace EmbeddedShaders {\n\n")
        
        # Write each shader as a byte array
        for shader_file in shader_files:
            var_name = shader_file.replace(".", "_")
            input_path = os.path.join(input_dir, shader_file)
            
            try:
                with open(input_path, "rb") as s:
                    content = s.read()
                    f.write(f"inline const unsigned char {var_name}_data[] = {{")
                    for i, b in enumerate(content):
                        if i % 12 == 0:
                            f.write("\n    ")
                        f.write(f"0x{b:02x}, ")
                    f.write("\n0x00 };\n") # Null terminator for safety if used as string
                    f.write(
                        f"inline const std::string {var_name}(reinterpret_cast<const char*>({var_name}_data), "
                        f"sizeof({var_name}_data) - 1);\n\n")
            except Exception as e:
                print(f"Warning: Could not read {shader_file}: {e}")

        # Add a lookup function
        f.write("inline std::string Get(const std::string& name) {\n")
        for shader_file in shader_files:
            var_name = shader_file.replace(".", "_")
            f.write(f"    if (name == \"{shader_file}\") return {var_name};\n")
        f.write("    return \"\";\n")
        f.write("}\n\n")
        
        f.write("} // namespace EmbeddedShaders\n")

if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root_dir = os.path.dirname(script_dir)

    input_dir = os.path.join(root_dir, "src", "RenderTab", "Shaders")
    default_output = os.path.join(root_dir, "build", "generated", "src", "RenderTab", "Shaders", "EmbeddedShaders.h")
    output_file = sys.argv[1] if len(sys.argv) > 1 else default_output

    bake_shaders(input_dir, output_file)
    print(f"Successfully baked shaders to {output_file}")
