import os


def write_bytes(out_file, data):
    for index, byte in enumerate(data):
        if index % 12 == 0:
            out_file.write("\n    ")
        out_file.write(f"0x{byte:02x}, ")


def bake_icons(input_specs, output_path):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as out_file:
        out_file.write("#pragma once\n\n")
        out_file.write("// This file is automatically generated. Do not edit manually.\n\n")
        out_file.write("namespace EmbeddedTabIcons {\n\n")

        for symbol_name, input_path in input_specs:
            data = b""
            if os.path.exists(input_path):
                try:
                    with open(input_path, "rb") as icon_file:
                        data = icon_file.read()
                except OSError as exc:
                    print(f"Warning: Could not read {input_path}: {exc}")
            else:
                print(f"Bake Notice: No tab icon found at {input_path}. Writing fallback bytes.")

            out_file.write(f"inline const unsigned char {symbol_name}_png_data[] = {{")
            if data:
                write_bytes(out_file, data)
            else:
                out_file.write("\n    0x00")
            out_file.write("\n};\n\n")
            out_file.write(f"inline const unsigned int {symbol_name}_png_size = {len(data)};\n\n")

        out_file.write("} // namespace EmbeddedTabIcons\n")


if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root_dir = os.path.dirname(script_dir)

    input_specs = [
        ("Editor", os.path.join(root_dir, "Icons", "Editor.png")),
        ("Library", os.path.join(root_dir, "Icons", "Library.png")),
        ("Render", os.path.join(root_dir, "Icons", "Render, Cube with points.png")),
        ("CharmLogo", os.path.join(root_dir, "Icons", "Charm logo icon.png")),
        ("NodeGraph", os.path.join(root_dir, "Icons", "node graph.png")),
        ("Export", os.path.join(root_dir, "Icons", "export.png")),
        ("Style", os.path.join(root_dir, "Icons", "paint brush.png")),
        ("Settings", os.path.join(root_dir, "Icons", "settings.png")),
        ("BackgroundRemover", os.path.join(root_dir, "Icons", "nodes", "background remover.png")),
        ("ColorGrade", os.path.join(root_dir, "Icons", "nodes", "3 color wheels.png")),
    ]
    output_file = os.path.join(root_dir, "src", "App", "Resources", "EmbeddedTabIcons.h")

    bake_icons(input_specs, output_file)
    print(f"Successfully baked tab icons to {output_file}")
