import os
import tempfile
from io import BytesIO


def write_bytes(out_file, data, trim_line_ends=False):
    for index, byte in enumerate(data):
        if index % 12 == 0:
            out_file.write("\n    ")
        out_file.write(f"0x{byte:02x},")
        if not trim_line_ends or (
            (index + 1) % 12 != 0 and index + 1 != len(data)
        ):
            out_file.write(" ")


def invert_png_rgb(data):
    """Invert an icon at bake time while preserving its alpha channel."""
    from PIL import Image, ImageOps

    with Image.open(BytesIO(data)) as image:
        rgba = image.convert("RGBA")
        red, green, blue, alpha = rgba.split()
        inverted = Image.merge("RGBA", (
            ImageOps.invert(red),
            ImageOps.invert(green),
            ImageOps.invert(blue),
            alpha,
        ))
        output = BytesIO()
        inverted.save(output, format="PNG")
        return output.getvalue()


def bake_icons(input_specs, output_path):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # Write beside the generated header and replace it only after the handle is
    # closed.  MSBuild/antivirus file observation can transiently reject a
    # truncate-open of the existing header on Windows.
    temporary = tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=os.path.dirname(output_path),
        prefix="EmbeddedTabIcons-",
        suffix=".tmp",
        delete=False,
    )
    temporary_path = temporary.name
    try:
        out_file = temporary
        out_file.write("#pragma once\n\n")
        out_file.write("// This file is automatically generated. Do not edit manually.\n\n")
        out_file.write("namespace EmbeddedTabIcons {\n\n")

        for symbol_name, input_path, *transforms in input_specs:
            data = b""
            if os.path.exists(input_path):
                try:
                    with open(input_path, "rb") as icon_file:
                        data = icon_file.read()
                    if "invert" in transforms:
                        data = invert_png_rgb(data)
                except OSError as exc:
                    print(f"Warning: Could not read {input_path}: {exc}")
            else:
                print(f"Bake Notice: No tab icon found at {input_path}. Writing fallback bytes.")

            out_file.write(f"inline const unsigned char {symbol_name}_png_data[] = {{")
            if data:
                write_bytes(out_file, data, symbol_name.startswith("File"))
            else:
                out_file.write("\n    0x00")
            out_file.write("\n};\n\n")
            out_file.write(f"inline const unsigned int {symbol_name}_png_size = {len(data)};\n\n")

        out_file.write("} // namespace EmbeddedTabIcons\n")
        out_file.close()
        os.replace(temporary_path, output_path)
    except Exception:
        temporary.close()
        try:
            os.remove(temporary_path)
        except OSError:
            pass
        raise


if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root_dir = os.path.dirname(script_dir)

    input_specs = [
        ("Editor", os.path.join(root_dir, "Icons", "Editor.png")),
        ("Library", os.path.join(root_dir, "Icons", "Library.png")),
        ("Render", os.path.join(root_dir, "Icons", "Render, Cube with points.png")),
        ("CharmLogo", os.path.join(root_dir, "Icons", "Charm logo icon.png")),
        ("NodeGraph", os.path.join(root_dir, "Icons", "node graph.png")),
        ("NodePresets", os.path.join(root_dir, "Icons", "node presets.png")),
        ("Export", os.path.join(root_dir, "Icons", "export.png")),
        ("Style", os.path.join(root_dir, "Icons", "paint brush.png")),
        ("Settings", os.path.join(root_dir, "Icons", "settings.png")),
        ("BackgroundRemover", os.path.join(root_dir, "Icons", "nodes", "background remover.png")),
        ("ColorGrade", os.path.join(root_dir, "Icons", "nodes", "3 color wheels.png")),
        ("ToneCurve", os.path.join(root_dir, "Icons", "tone curve.png")),
        ("ViewTransform", os.path.join(root_dir, "Icons", "view transform.png")),
        ("HdrMerge", os.path.join(root_dir, "Icons", "hdr merge.png")),
        ("CustomMask", os.path.join(root_dir, "Icons", "custom mask.png")),
        ("Lut", os.path.join(root_dir, "Icons", "LUT.png")),
        ("Denoise", os.path.join(root_dir, "Icons", "denoise.png")),
        ("RawFolder", os.path.join(root_dir, "Icons", "Raw Tab", "folder.png")),
        ("RawRefresh", os.path.join(root_dir, "Icons", "Raw Tab", "refresh.png")),
        ("RawClear", os.path.join(root_dir, "Icons", "Raw Tab", "x.png")),
        ("RawGrid", os.path.join(root_dir, "Icons", "Raw Tab", "grid.png")),
        ("RawList", os.path.join(root_dir, "Icons", "Raw Tab", "list.png")),
        ("RawGallery", os.path.join(root_dir, "Icons", "Raw Tab", "gallery.png")),
        ("RawLab", os.path.join(root_dir, "Icons", "Raw Tab", "Lab", "raw-lab.png")),
        ("RawLabLight", os.path.join(root_dir, "Icons", "Raw Tab", "Lab", "light.png")),
        ("RawLabZones", os.path.join(root_dir, "Icons", "Raw Tab", "Lab", "zones.png")),
        ("RawLabSave", os.path.join(root_dir, "Icons", "Raw Tab", "Lab", "save.png")),
        ("RawLabReset", os.path.join(root_dir, "Icons", "Raw Tab", "Lab", "reset.png")),
        ("RawLabTarget", os.path.join(root_dir, "Icons", "Raw Tab", "Lab", "target.png")),
        ("RawLabFilmstrip", os.path.join(root_dir, "Icons", "Raw Tab", "Lab", "filmstrip.png")),
        ("RawLabWorkspaceGallery", os.path.join(root_dir, "Icons", "Raw Tab", "Lab", "workspace-gallery.png")),
        ("RawLabFinalView", os.path.join(root_dir, "Icons", "Raw Tab", "Lab", "final-view.png")),
        ("RawLabCompare", os.path.join(root_dir, "Icons", "Raw Tab", "Lab", "compare.png")),
        ("RawLabAffected", os.path.join(root_dir, "Icons", "Raw Tab", "Lab", "affected.png")),
        ("RawLabDelta", os.path.join(root_dir, "Icons", "Raw Tab", "Lab", "delta.png")),
        ("RawLabHighlightRisk", os.path.join(root_dir, "Icons", "Raw Tab", "Lab", "highlight-risk.png")),
        ("RawLabInspect", os.path.join(root_dir, "Icons", "Raw Tab", "Lab", "inspect.png")),
        ("RawLabFitView", os.path.join(root_dir, "Icons", "Raw Tab", "Lab", "fit-view.png")),
        ("PopoutCanvasWindow", os.path.join(root_dir, "Icons", "popout canvas window.png"), "invert"),
        ("FileNew", os.path.join(root_dir, "Icons", "File Dialog", "new.png")),
        ("FileOpenProject", os.path.join(root_dir, "Icons", "File Dialog", "open project.png")),
        ("FileSave", os.path.join(root_dir, "Icons", "File Dialog", "save.png")),
        ("FileExitProgram", os.path.join(root_dir, "Icons", "File Dialog", "exit program.png")),
        ("ProgramIcon", os.path.join(root_dir, "website", "program icon.png")),
    ]
    output_file = os.path.join(root_dir, "src", "App", "Resources", "EmbeddedTabIcons.h")

    bake_icons(input_specs, output_file)
    print(f"Successfully baked tab icons to {output_file}")

    # Automatically generate the Windows .ico file if the program icon is modified
    try:
        from PIL import Image
        program_icon_path = os.path.join(root_dir, "website", "program icon.png")
        ico_output_path = os.path.join(root_dir, "src", "Stack.ico")
        if os.path.exists(program_icon_path):
            img = Image.open(program_icon_path)
            img.save(ico_output_path, format='ICO', sizes=[(16, 16), (32, 32), (48, 48), (256, 256)])
            print(f"Successfully updated Windows executable icon at {ico_output_path}")
    except Exception as e:
        print(f"Warning: Could not automatically generate Windows executable icon: {e}")
