import os


def write_embedded_font(input_path, output_path):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(input_path, "rb") as source:
        content = source.read()

    with open(output_path, "w", encoding="utf-8") as target:
        target.write("#pragma once\n\n")
        target.write("// This file is automatically generated. Do not edit manually.\n")
        target.write("#include <cstddef>\n\n")
        target.write("namespace EmbeddedCompositeFont {\n\n")
        target.write("inline const unsigned char kRobotoMediumTtf[] = {")
        for index, byte in enumerate(content):
            if index % 12 == 0:
                target.write("\n    ")
            target.write(f"0x{byte:02x}, ")
        target.write("\n};\n\n")
        target.write("inline constexpr std::size_t kRobotoMediumTtfSize = sizeof(kRobotoMediumTtf);\n\n")
        target.write("} // namespace EmbeddedCompositeFont\n")


if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root_dir = os.path.dirname(script_dir)
    input_path = os.path.join(root_dir, "Assets", "Fonts", "Roboto-Medium.ttf")
    output_path = os.path.join(root_dir, "src", "Composite", "EmbeddedCompositeFont.h")

    write_embedded_font(input_path, output_path)
    print(f"Successfully baked composite font to {output_path}")
