import os
import sys

def bake_image(input_path, output_path):
    # Ensure directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    data = []
    if os.path.exists(input_path):
        try:
            with open(input_path, "rb") as f:
                data = f.read()
        except Exception as e:
            print(f"Warning: Could not read {input_path}: {e}")
    else:
        print(f"Bake Notice: No splash image found at {input_path}. Creating fallback header.")

    with open(output_path, "w") as f:
        f.write("#pragma once\n\n")
        f.write("// This file is automatically generated. Do not edit manually.\n\n")
        f.write(f"static const unsigned char splash_data[] = {{")
        
        # Write bytes in hex format
        for i, b in enumerate(data):
            if i % 12 == 0:
                f.write("\n    ")
            f.write(f"0x{b:02x}, ")
        
        # If empty, add a dummy 0 byte to avoid potential compiler issues with empty arrays
        if not data:
            f.write("0x00")
            
        f.write("\n};\n\n")
        f.write(f"static const unsigned int splash_size = {len(data)};\n")

if __name__ == "__main__":
    # Default paths relative to project root
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root_dir = os.path.dirname(script_dir)
    
    input_file = os.path.join(root_dir, "Assets", "Splash", "splash_banner.png")
    output_file = os.path.join(root_dir, "src", "App", "Resources", "EmbeddedSplash.h")
    
    bake_image(input_file, output_file)
    print(f"Successfully baked image to {output_file}")
